name: AWD
version: 2.6.1 alpha
main: com.gmail.davideblade99.AWD.bukkit.AWD
author: DavideBlade
description: Prevent stealing of your maps!
load: POSTWORLD
#TODO website: https://www.spigotmc.org/resources/antiworlddownloader.23022/
database: false
commands:
  awd:
    usage: /<command> [help]
    description: Plugin information.

permissions:
  antiwdl.allow:
    description: Gives access to join with WorldDownloader mod.
    default: op