name: AWD
version: ${project.version}
main: com.gmail.davideblade99.AWD.bukkit.AWD
author: DavideBlade
description: ${project.description}
load: POSTWORLD
website: https://www.spigotmc.org/resources/antiworlddownloader.99356/
database: false
commands:
  awd:
    usage: /<command> [help]
    description: Plugin information.

permissions:
  antiwdl.allow:
    description: Gives access to join with WorldDownloader mod.
    default: op